{"name": "Проверка: нельзя авторизоваться в системе с несуществующим логином и существующим паролем", "status": "passed", "description": "Запрос POST на /api/v1/courier/login с несуществующим логином и существующим паролем вернет 404 Not Found", "start": 1742218810253, "stop": 1742218810591, "uuid": "69ddc438-acba-43b2-a822-2b1a7389204d", "historyId": "74ecab81dfbaecab76dfd48f34a60e47", "testCaseId": "74ecab81dfbaecab76dfd48f34a60e47", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_wrong_login_return_404_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-FO1K8TG"}, {"name": "thread", "value": "14656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}