{"name": "Проверка: нельзя авторизоваться в системе с существующим логином и несуществующим паролем", "status": "passed", "description": "Запрос POST на /api/v1/courier/login с существующим логином и несуществующим паролем вернет 404 Not Found", "start": 1742111083918, "stop": 1742111084277, "uuid": "c36f988d-6611-43fd-bdeb-825fbfcd48e4", "historyId": "478ad18f80b4331dde68f942a0365020", "testCaseId": "478ad18f80b4331dde68f942a0365020", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_wrong_password_return_404_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-FO1K8TG"}, {"name": "thread", "value": "15228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}